baseURL = "https://officialasishkumar.github.io/"
languageCode = 'en-us'
title = 'Asish Kumar - Student in India'
theme = 'devise'
enableEmoji = true
relativeURLs = true
enableRobotsTXT = true
copyright = '&copy; Copyright 2024, Asish Kumar'

[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    title = "Blogs"
    url = "/Blogs/"
    weight = -100

[params] 
    header_title = "Asish Kumar"
    header_subtitle = "Student | 🇮🇳"
    recent_posts = 5
    [params.style]                             # CSS style overrides
        backgroundColor = '#131418'
        homeImageBorderColor = '#ffffff'
        fontFamilyBase = 'Roboto' 
        fontColor = '#babdc4'
    [[params.social]]
        fa_icon = "fab fa-linkedin-in fa-1x"
        href = "https://www.linkedin.com/in/asish-kr/"
    [[params.social]]
        fa_icon = "fab fa-github fa-1x"
        href = "http://github.com/officialasishkumar"
    [[params.social]] 
        fa_icon = "fas fa-coffee fa-1x"
        href = "https://www.buymeacoffee.com/asishkumar"

[services]
  [services.googleAnalytics]
    ID = 'G-7VBR15LLC5'
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
