baseURL = "https://officialasishkumar.github.io/tardis-profiling-report/"
languageCode = 'en-us'
title = 'TARDIS-SN Profiling Report'
theme = 'devise'
enableEmoji = true
relativeURLs = true
enableRobotsTXT = true
copyright = '&copy; Copyright 2024, TARDIS-SN'

[menu]
  [[menu.main]]
    identifier = "profiling-report"
    name = "Profiling"
    title = "Profiling"
    url = "/tardis-profiling-report/"
    weight = -100

[params] 
    header_title = "TARDIS-SN"
    header_subtitle = "Author: Asish Kumar"
    [params.style]                             # CSS style overrides
        backgroundColor = '#131418'
        homeImageBorderColor = '#ffffff'
        fontFamilyBase = 'Roboto' 
        fontColor = '#babdc4'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files