languageCode = 'en-us'
title = 'TARDIS Profiling report'
theme = 'devise'
enableEmoji = true
relativeURLs = true
enableRobotsTXT = true
copyright = '&copy; Copyright 2024, TARDIS-SN'

[menu]
  [[menu.main]]
    identifier = "Profiling Report"
    name = "Profiling Report"
    title = "Profiling Report"
    url = "/profiling-report/"
    weight = -100

[params] 
    header_title = "TARDIS-SN"
    header_subtitle = "GSoC 2024"
    recent_posts = 5
    [params.style]                             # CSS style overrides
        backgroundColor = '#7C93C3'
        homeImageBorderColor = '#ffffff'
        fontFamilyBase = 'Helvetica Neue' 
        fontColor = '#212529'
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
